### ISSUE TITLE
System.IndexOutOfRangeException on high volumetry

### ISSUE THREAD

**Issue by thecoachfr** [lemire/csharpewah#13] opened 2019-06-10 15:37 UTC
Hi,

I use the library to index message and then be able to launch queries. I had to deal with 100.000+ messages to index. But the problem arises with much lower volumetry.
The exception raises in:
```
    public ulong GetCardinality() {
                ulong counter = 0;
                var i = new EwahEnumerator(_Buffer, _ActualSizeInWords);
                while (i.HasNext()) {
                    RunningLengthWord localrlw = i.Next();
                    if (localrlw.RunningBit) {
                       counter += (ulong)(WordInBits * localrlw.RunningLength);
                    }
                   for (int j = 0; j < localrlw.NumberOfLiteralWords; ++j) {
                       long data = i.Buffer[i.DirtyWords + j];
                       counter += bitCount((ulong)data);
                   }
               }
              return counter;
           }
```
And more precisely in " i.Buffer[i.DirtyWords + j];".
Of course, I'm not able to reproduce outside my application.
I had the feeling that the bitarray is corrupted (at least EwahEnumerator behaves strangely), but can't prove it and can't explain it.

Does my problem ring the bell at someone?
Thanks.

Alexandre.

.NET Core on Windows 10

**Comment by lemire** [comment] 2019-06-10 15:52
Can you dump the content of the words? Maybe as a series of hexadecimal values?

**Comment by thecoachfr** [comment] 2019-06-11 08:23
Hello, sorry not really readable, but the best I can have:

  | Nom | Valeur | Type
-- | -- | -- | --
  | SizeInBits | 3024 | int
  | SizeInBytes | 280 | int
  | _ActualSizeInWords | 35 | int
◢ | _Buffer | {long[35]} | long[]
  | [0] | 17179869184 | long
  | [1] | -281474976710656 | long
  | [2] | 4294967295 | long
  | [3] | 17179869188 | long
  | [4] | -4294967296 | long
  | [5] | 65535 | long
  | [6] | 8589934595 | long
  | [7] | 4294967295 | long
  | [8] | 17179869186 | long
  | [9] | -281474976710656 | long
  | [10] | 4294967295 | long
  | [11] | 8589934596 | long
  | [12] | -4294967296 | long
  | [13] | 8589934595 | long
  | [14] | 281474976710655 | long
  | [15] | 17179869200 | long
  | [16] | -281474976710656 | long
  | [17] | 4294967295 | long
  | [18] | 25769803790 | long
  | [19] | 281474976710655 | long
  | [20] | -4294967296 | long
  | [21] | 65535 | long
  | [22] | 17179869192 | long
  | [23] | -4294967296 | long
  | [24] | 65535 | long
  | [25] | 0 | long
  | [26] | 8589934594 | long
  | [27] | 4294967296 | long
  | [28] | -8589934592 | long
  | [29] | 8589934595 | long
  | [30] | -6917810502617792513 | long
  | [31] | 34359738366 | long
  | [32] | 4611686018427387904 | long
  | [33] | -140737488364033 | long
  | [34] | 65535 | long
◢ | _Rlw | {running bit = False running length = 4294967295 number of lit. words 3} | Ewah.RunningLengthWord
  | ◢ ArrayOfWords | {long[35]} | long[]
  | [0] | 17179869184 | long
  | [1] | -281474976710656 | long
  | [2] | 4294967295 | long
  | [3] | 17179869188 | long
  | [4] | -4294967296 | long
  | [5] | 65535 | long
  | [6] | 8589934595 | long
  | [7] | 4294967295 | long
  | [8] | 17179869186 | long
  | [9] | -281474976710656 | long
  | [10] | 4294967295 | long
  | [11] | 8589934596 | long
  | [12] | -4294967296 | long
  | [13] | 8589934595 | long
  | [14] | 281474976710655 | long
  | [15] | 17179869200 | long
  | [16] | -281474976710656 | long
  | [17] | 4294967295 | long
  | [18] | 25769803790 | long
  | [19] | 281474976710655 | long
  | [20] | -4294967296 | long
  | [21] | 65535 | long
  | [22] | 17179869192 | long
  | [23] | -4294967296 | long
  | [24] | 65535 | long
  | [25] | 0 | long
  | [26] | 8589934594 | long
  | [27] | 4294967296 | long
  | [28] | -8589934592 | long
  | [29] | 8589934595 | long
  | [30] | -6917810502617792513 | long
  | [31] | 34359738366 | long
  | [32] | 4611686018427387904 | long
  | [33] | -140737488364033 | long
  | [34] | 65535 | long
  | Count | 4294967298 | long
  | NumberOfLiteralWords | 3 | long
  | Position | 31 | int
  | RunningBit | false | bool
  | RunningLength | 4294967295 | long
  | ▶ Static members |   |

**Comment by lemire** [comment] 2019-06-11 13:50
That should help.

**Comment by lemire** [comment] 2019-06-13 22:16
Ok. So the first word is a marker word and it indicates that there are two literal words following it. Since 17179869184 >> 33 is 2. The next marker word is 17179869188, again it indicates two literal words.  The next marker word is 8589934595. It indicates 1 literal word. The next marker word is 17179869186. Then 8589934596. Then 8589934595. ... Up to -8589934592... which points to 2147483647 literal words following it.


So this buffer is not in valid EWAH.

Can you give tell us how it was produced? That is, how does your application constructs it? Can you provide a code sample that ends up generating this buffer?

Note: If your application is multithreaded, make sure to use locks where appropriate.

**Comment by lemire** [comment] 2019-06-13 23:22
Note that multithreading or other concurrency issues are most likely. It is possible that there is a bug in the library that causes corruption, but if your application is not single-threaded, the most likely explanation is that you have different threads/cores modifying the same data... which is unsafe in this case.

**Comment by lemire** [comment] 2019-06-14 19:45
I am going to close this on the assumption that you have a concurrency issue. Please reopen if you can reproduce with single-threaded code.

**Closed by lemire** 2019-06-14 19:45 UTC
